### ISSUE TITLE
Caption on grid looking aweful

### ISSUE THREAD

**Issue by enterprisebug** [enterprisebug/grid.js#1]
When activating the caption it shows on the grid, but looks disgusting.
The should be an improvement on this.

**Comment by t3dodson** [comment]
+1 I think its more for debugging than actually using in a final project.

**Comment by asannes32** [comment]
It would also be nice to specify where they start on the grid. 

I would have a use for these in a final project, but would want to be able to configure it to my needs (in my case, I would need them to start in the bottom left corner).

The ability to choose only horizontal or vertical captions would be nice too.

**Comment by enterprisebug** [comment]
just added horizontalLines and verticalLines switch
