### ISSUE TITLE
Only works correct for grids with more width than height.

### ISSUE THREAD

**Issue by muellerdennis** [enterprisebug/grid.js#3]
I fixed it for myself changing this:
for (var y = 0; y <= target.canvas.width; y += o.distance) {

to this:
if (target.canvas.width > target.canvas.height) {
    until = target.canvas.width;
}else{
    until = target.canvas.height;
}

for (var y = 0; y <= until; y += o.distance) {

**Comment by enterprisebug** [comment]
Thanks for the hint. I fixed it with your code.
